/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as CommencerRouteImport } from './routes/commencer'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as SimulateurRouteImport } from './routes/simulateur'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCreationRouteImport } from './routes/_authenticated/creation'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedMonCompteRouteImport } from './routes/_authenticated/mon-compte'
import { Route as AuthenticatedTableauDeBordRouteImport } from './routes/_authenticated/tableau-de-bord'
import { Route as SignerJetonRouteImport } from './routes/signer.$jeton'
import { Route as AuthenticatedCabinetIndexRouteImport } from './routes/_authenticated/cabinet.index'
import { Route as AuthenticatedCabinetIdRouteImport } from './routes/_authenticated/cabinet.$id'
import { Route as AuthenticatedCabinetRappelsRouteImport } from './routes/_authenticated/cabinet.rappels'
import { Route as ApiPublicHooksPurgeDonneesRouteImport } from './routes/api/public/hooks/purge-donnees'
import { Route as ApiPublicHooksRelanceSignaturesRouteImport } from './routes/api/public/hooks/relance-signatures'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const CommencerRoute = CommencerRouteImport.update({
  id: '/commencer',
  path: '/commencer',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulateurRoute = SimulateurRouteImport.update({
  id: '/simulateur',
  path: '/simulateur',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreationRoute = AuthenticatedCreationRouteImport.update({
  id: '/creation',
  path: '/creation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonCompteRoute = AuthenticatedMonCompteRouteImport.update({
  id: '/mon-compte',
  path: '/mon-compte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTableauDeBordRoute =
  AuthenticatedTableauDeBordRouteImport.update({
    id: '/tableau-de-bord',
    path: '/tableau-de-bord',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const SignerJetonRoute = SignerJetonRouteImport.update({
  id: '/signer/$jeton',
  path: '/signer/$jeton',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCabinetIndexRoute =
  AuthenticatedCabinetIndexRouteImport.update({
    id: '/cabinet/',
    path: '/cabinet/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCabinetIdRoute = AuthenticatedCabinetIdRouteImport.update({
  id: '/cabinet/$id',
  path: '/cabinet/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCabinetRappelsRoute =
  AuthenticatedCabinetRappelsRouteImport.update({
    id: '/cabinet/rappels',
    path: '/cabinet/rappels',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksPurgeDonneesRoute =
  ApiPublicHooksPurgeDonneesRouteImport.update({
    id: '/api/public/hooks/purge-donnees',
    path: '/api/public/hooks/purge-donnees',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRelanceSignaturesRoute =
  ApiPublicHooksRelanceSignaturesRouteImport.update({
    id: '/api/public/hooks/relance-signatures',
    path: '/api/public/hooks/relance-signatures',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cgu': typeof CguRoute
  '/cgv': typeof CgvRoute
  '/commencer': typeof CommencerRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/simulateur': typeof SimulateurRoute
  '/tarifs': typeof TarifsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/creation': typeof AuthenticatedCreationRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/mon-compte': typeof AuthenticatedMonCompteRoute
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/signer/$jeton': typeof SignerJetonRoute
  '/cabinet/$id': typeof AuthenticatedCabinetIdRoute
  '/cabinet/rappels': typeof AuthenticatedCabinetRappelsRoute
  '/cabinet/': typeof AuthenticatedCabinetIndexRoute
  '/api/public/hooks/purge-donnees': typeof ApiPublicHooksPurgeDonneesRoute
  '/api/public/hooks/relance-signatures': typeof ApiPublicHooksRelanceSignaturesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cgu': typeof CguRoute
  '/cgv': typeof CgvRoute
  '/commencer': typeof CommencerRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/simulateur': typeof SimulateurRoute
  '/tarifs': typeof TarifsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/creation': typeof AuthenticatedCreationRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/mon-compte': typeof AuthenticatedMonCompteRoute
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/signer/$jeton': typeof SignerJetonRoute
  '/cabinet/$id': typeof AuthenticatedCabinetIdRoute
  '/cabinet/rappels': typeof AuthenticatedCabinetRappelsRoute
  '/cabinet': typeof AuthenticatedCabinetIndexRoute
  '/api/public/hooks/purge-donnees': typeof ApiPublicHooksPurgeDonneesRoute
  '/api/public/hooks/relance-signatures': typeof ApiPublicHooksRelanceSignaturesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cgu': typeof CguRoute
  '/cgv': typeof CgvRoute
  '/commencer': typeof CommencerRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/simulateur': typeof SimulateurRoute
  '/tarifs': typeof TarifsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/creation': typeof AuthenticatedCreationRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/mon-compte': typeof AuthenticatedMonCompteRoute
  '/_authenticated/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/signer/$jeton': typeof SignerJetonRoute
  '/_authenticated/cabinet/$id': typeof AuthenticatedCabinetIdRoute
  '/_authenticated/cabinet/rappels': typeof AuthenticatedCabinetRappelsRoute
  '/_authenticated/cabinet/': typeof AuthenticatedCabinetIndexRoute
  '/api/public/hooks/purge-donnees': typeof ApiPublicHooksPurgeDonneesRoute
  '/api/public/hooks/relance-signatures': typeof ApiPublicHooksRelanceSignaturesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cgu'
    | '/cgv'
    | '/commencer'
    | '/confidentialite'
    | '/mentions-legales'
    | '/simulateur'
    | '/tarifs'
    | '/admin'
    | '/creation'
    | '/documents'
    | '/mon-compte'
    | '/tableau-de-bord'
    | '/signer/$jeton'
    | '/cabinet/$id'
    | '/cabinet/rappels'
    | '/cabinet/'
    | '/api/public/hooks/purge-donnees'
    | '/api/public/hooks/relance-signatures'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cgu'
    | '/cgv'
    | '/commencer'
    | '/confidentialite'
    | '/mentions-legales'
    | '/simulateur'
    | '/tarifs'
    | '/admin'
    | '/creation'
    | '/documents'
    | '/mon-compte'
    | '/tableau-de-bord'
    | '/signer/$jeton'
    | '/cabinet/$id'
    | '/cabinet/rappels'
    | '/cabinet'
    | '/api/public/hooks/purge-donnees'
    | '/api/public/hooks/relance-signatures'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cgu'
    | '/cgv'
    | '/commencer'
    | '/confidentialite'
    | '/mentions-legales'
    | '/simulateur'
    | '/tarifs'
    | '/_authenticated/admin'
    | '/_authenticated/creation'
    | '/_authenticated/documents'
    | '/_authenticated/mon-compte'
    | '/_authenticated/tableau-de-bord'
    | '/signer/$jeton'
    | '/_authenticated/cabinet/$id'
    | '/_authenticated/cabinet/rappels'
    | '/_authenticated/cabinet/'
    | '/api/public/hooks/purge-donnees'
    | '/api/public/hooks/relance-signatures'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CguRoute: typeof CguRoute
  CgvRoute: typeof CgvRoute
  CommencerRoute: typeof CommencerRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  SimulateurRoute: typeof SimulateurRoute
  TarifsRoute: typeof TarifsRoute
  SignerJetonRoute: typeof SignerJetonRoute
  ApiPublicHooksPurgeDonneesRoute: typeof ApiPublicHooksPurgeDonneesRoute
  ApiPublicHooksRelanceSignaturesRoute: typeof ApiPublicHooksRelanceSignaturesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commencer': {
      id: '/commencer'
      path: '/commencer'
      fullPath: '/commencer'
      preLoaderRoute: typeof CommencerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulateur': {
      id: '/simulateur'
      path: '/simulateur'
      fullPath: '/simulateur'
      preLoaderRoute: typeof SimulateurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/creation': {
      id: '/_authenticated/creation'
      path: '/creation'
      fullPath: '/creation'
      preLoaderRoute: typeof AuthenticatedCreationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon-compte': {
      id: '/_authenticated/mon-compte'
      path: '/mon-compte'
      fullPath: '/mon-compte'
      preLoaderRoute: typeof AuthenticatedMonCompteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tableau-de-bord': {
      id: '/_authenticated/tableau-de-bord'
      path: '/tableau-de-bord'
      fullPath: '/tableau-de-bord'
      preLoaderRoute: typeof AuthenticatedTableauDeBordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/signer/$jeton': {
      id: '/signer/$jeton'
      path: '/signer/$jeton'
      fullPath: '/signer/$jeton'
      preLoaderRoute: typeof SignerJetonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cabinet/': {
      id: '/_authenticated/cabinet/'
      path: '/cabinet'
      fullPath: '/cabinet/'
      preLoaderRoute: typeof AuthenticatedCabinetIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cabinet/$id': {
      id: '/_authenticated/cabinet/$id'
      path: '/cabinet/$id'
      fullPath: '/cabinet/$id'
      preLoaderRoute: typeof AuthenticatedCabinetIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cabinet/rappels': {
      id: '/_authenticated/cabinet/rappels'
      path: '/cabinet/rappels'
      fullPath: '/cabinet/rappels'
      preLoaderRoute: typeof AuthenticatedCabinetRappelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/purge-donnees': {
      id: '/api/public/hooks/purge-donnees'
      path: '/api/public/hooks/purge-donnees'
      fullPath: '/api/public/hooks/purge-donnees'
      preLoaderRoute: typeof ApiPublicHooksPurgeDonneesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/relance-signatures': {
      id: '/api/public/hooks/relance-signatures'
      path: '/api/public/hooks/relance-signatures'
      fullPath: '/api/public/hooks/relance-signatures'
      preLoaderRoute: typeof ApiPublicHooksRelanceSignaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCreationRoute: typeof AuthenticatedCreationRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedMonCompteRoute: typeof AuthenticatedMonCompteRoute
  AuthenticatedTableauDeBordRoute: typeof AuthenticatedTableauDeBordRoute
  AuthenticatedCabinetIdRoute: typeof AuthenticatedCabinetIdRoute
  AuthenticatedCabinetRappelsRoute: typeof AuthenticatedCabinetRappelsRoute
  AuthenticatedCabinetIndexRoute: typeof AuthenticatedCabinetIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCreationRoute: AuthenticatedCreationRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedMonCompteRoute: AuthenticatedMonCompteRoute,
  AuthenticatedTableauDeBordRoute: AuthenticatedTableauDeBordRoute,
  AuthenticatedCabinetIdRoute: AuthenticatedCabinetIdRoute,
  AuthenticatedCabinetRappelsRoute: AuthenticatedCabinetRappelsRoute,
  AuthenticatedCabinetIndexRoute: AuthenticatedCabinetIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CguRoute: CguRoute,
  CgvRoute: CgvRoute,
  CommencerRoute: CommencerRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  SimulateurRoute: SimulateurRoute,
  TarifsRoute: TarifsRoute,
  SignerJetonRoute: SignerJetonRoute,
  ApiPublicHooksPurgeDonneesRoute: ApiPublicHooksPurgeDonneesRoute,
  ApiPublicHooksRelanceSignaturesRoute: ApiPublicHooksRelanceSignaturesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
