/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as CommencerRouteImport } from './routes/commencer'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as RendezVousRouteImport } from './routes/rendez-vous'
import { Route as SimulateurRouteImport } from './routes/simulateur'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCreationRouteImport } from './routes/_authenticated/creation'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedMonCompteRouteImport } from './routes/_authenticated/mon-compte'
import { Route as AuthenticatedSimulationsRouteImport } from './routes/_authenticated/simulations'
import { Route as AuthenticatedTableauDeBordRouteImport } from './routes/_authenticated/tableau-de-bord'
import { Route as AuthenticatedVerificationFinaleRouteImport } from './routes/_authenticated/verification-finale'
import { Route as DevApercuStatutsRouteImport } from './routes/dev.apercu-statuts'
import { Route as DevAssocieDateRouteImport } from './routes/dev.associe-date'
import { Route as DevConformiteRouteImport } from './routes/dev.conformite'
import { Route as DevDenominationRouteImport } from './routes/dev.denomination'
import { Route as DevWordingDenominationRouteImport } from './routes/dev.wording-denomination'
import { Route as SignerJetonRouteImport } from './routes/signer.$jeton'
import { Route as AuthenticatedCabinetIndexRouteImport } from './routes/_authenticated/cabinet.index'
import { Route as AuthenticatedCabinetIdRouteImport } from './routes/_authenticated/cabinet.$id'
import { Route as AuthenticatedCabinetConformiteRouteImport } from './routes/_authenticated/cabinet.conformite'
import { Route as AuthenticatedCabinetContactsRouteImport } from './routes/_authenticated/cabinet.contacts'
import { Route as AuthenticatedCabinetDenominationsRouteImport } from './routes/_authenticated/cabinet.denominations'
import { Route as AuthenticatedCabinetDonneesTestRouteImport } from './routes/_authenticated/cabinet.donnees-test'
import { Route as AuthenticatedCabinetEmailsTestRouteImport } from './routes/_authenticated/cabinet.emails-test'
import { Route as AuthenticatedCabinetRappelsRouteImport } from './routes/_authenticated/cabinet.rappels'
import { Route as ApiPublicEmailsTestRouteImport } from './routes/api/public/emails-test'
import { Route as ApiPublicEmailsTestConfirmerRouteImport } from './routes/api/public/emails-test.confirmer'
import { Route as ApiPublicHooksPurgeDonneesRouteImport } from './routes/api/public/hooks/purge-donnees'
import { Route as ApiPublicHooksRelancePiecesRouteImport } from './routes/api/public/hooks/relance-pieces'
import { Route as ApiPublicHooksRelanceSignaturesRouteImport } from './routes/api/public/hooks/relance-signatures'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const CommencerRoute = CommencerRouteImport.update({
  id: '/commencer',
  path: '/commencer',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const RendezVousRoute = RendezVousRouteImport.update({
  id: '/rendez-vous',
  path: '/rendez-vous',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulateurRoute = SimulateurRouteImport.update({
  id: '/simulateur',
  path: '/simulateur',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreationRoute = AuthenticatedCreationRouteImport.update({
  id: '/creation',
  path: '/creation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonCompteRoute = AuthenticatedMonCompteRouteImport.update({
  id: '/mon-compte',
  path: '/mon-compte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSimulationsRoute =
  AuthenticatedSimulationsRouteImport.update({
    id: '/simulations',
    path: '/simulations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTableauDeBordRoute =
  AuthenticatedTableauDeBordRouteImport.update({
    id: '/tableau-de-bord',
    path: '/tableau-de-bord',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVerificationFinaleRoute =
  AuthenticatedVerificationFinaleRouteImport.update({
    id: '/verification-finale',
    path: '/verification-finale',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const DevApercuStatutsRoute = DevApercuStatutsRouteImport.update({
  id: '/dev/apercu-statuts',
  path: '/dev/apercu-statuts',
  getParentRoute: () => rootRouteImport,
} as any)
const DevAssocieDateRoute = DevAssocieDateRouteImport.update({
  id: '/dev/associe-date',
  path: '/dev/associe-date',
  getParentRoute: () => rootRouteImport,
} as any)
const DevConformiteRoute = DevConformiteRouteImport.update({
  id: '/dev/conformite',
  path: '/dev/conformite',
  getParentRoute: () => rootRouteImport,
} as any)
const DevDenominationRoute = DevDenominationRouteImport.update({
  id: '/dev/denomination',
  path: '/dev/denomination',
  getParentRoute: () => rootRouteImport,
} as any)
const DevWordingDenominationRoute = DevWordingDenominationRouteImport.update({
  id: '/dev/wording-denomination',
  path: '/dev/wording-denomination',
  getParentRoute: () => rootRouteImport,
} as any)
const SignerJetonRoute = SignerJetonRouteImport.update({
  id: '/signer/$jeton',
  path: '/signer/$jeton',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCabinetIndexRoute =
  AuthenticatedCabinetIndexRouteImport.update({
    id: '/cabinet/',
    path: '/cabinet/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCabinetIdRoute = AuthenticatedCabinetIdRouteImport.update({
  id: '/cabinet/$id',
  path: '/cabinet/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCabinetConformiteRoute =
  AuthenticatedCabinetConformiteRouteImport.update({
    id: '/cabinet/conformite',
    path: '/cabinet/conformite',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCabinetContactsRoute =
  AuthenticatedCabinetContactsRouteImport.update({
    id: '/cabinet/contacts',
    path: '/cabinet/contacts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCabinetDenominationsRoute =
  AuthenticatedCabinetDenominationsRouteImport.update({
    id: '/cabinet/denominations',
    path: '/cabinet/denominations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCabinetDonneesTestRoute =
  AuthenticatedCabinetDonneesTestRouteImport.update({
    id: '/cabinet/donnees-test',
    path: '/cabinet/donnees-test',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCabinetEmailsTestRoute =
  AuthenticatedCabinetEmailsTestRouteImport.update({
    id: '/cabinet/emails-test',
    path: '/cabinet/emails-test',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCabinetRappelsRoute =
  AuthenticatedCabinetRappelsRouteImport.update({
    id: '/cabinet/rappels',
    path: '/cabinet/rappels',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicEmailsTestRoute = ApiPublicEmailsTestRouteImport.update({
  id: '/api/public/emails-test',
  path: '/api/public/emails-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEmailsTestConfirmerRoute =
  ApiPublicEmailsTestConfirmerRouteImport.update({
    id: '/confirmer',
    path: '/confirmer',
    getParentRoute: () => ApiPublicEmailsTestRoute,
  } as any)
const ApiPublicHooksPurgeDonneesRoute =
  ApiPublicHooksPurgeDonneesRouteImport.update({
    id: '/api/public/hooks/purge-donnees',
    path: '/api/public/hooks/purge-donnees',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRelancePiecesRoute =
  ApiPublicHooksRelancePiecesRouteImport.update({
    id: '/api/public/hooks/relance-pieces',
    path: '/api/public/hooks/relance-pieces',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRelanceSignaturesRoute =
  ApiPublicHooksRelanceSignaturesRouteImport.update({
    id: '/api/public/hooks/relance-signatures',
    path: '/api/public/hooks/relance-signatures',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cgu': typeof CguRoute
  '/cgv': typeof CgvRoute
  '/commencer': typeof CommencerRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/rendez-vous': typeof RendezVousRoute
  '/simulateur': typeof SimulateurRoute
  '/tarifs': typeof TarifsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/creation': typeof AuthenticatedCreationRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/mon-compte': typeof AuthenticatedMonCompteRoute
  '/simulations': typeof AuthenticatedSimulationsRoute
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/verification-finale': typeof AuthenticatedVerificationFinaleRoute
  '/dev/apercu-statuts': typeof DevApercuStatutsRoute
  '/dev/associe-date': typeof DevAssocieDateRoute
  '/dev/conformite': typeof DevConformiteRoute
  '/dev/denomination': typeof DevDenominationRoute
  '/dev/wording-denomination': typeof DevWordingDenominationRoute
  '/signer/$jeton': typeof SignerJetonRoute
  '/cabinet/$id': typeof AuthenticatedCabinetIdRoute
  '/cabinet/conformite': typeof AuthenticatedCabinetConformiteRoute
  '/cabinet/contacts': typeof AuthenticatedCabinetContactsRoute
  '/cabinet/denominations': typeof AuthenticatedCabinetDenominationsRoute
  '/cabinet/donnees-test': typeof AuthenticatedCabinetDonneesTestRoute
  '/cabinet/emails-test': typeof AuthenticatedCabinetEmailsTestRoute
  '/cabinet/rappels': typeof AuthenticatedCabinetRappelsRoute
  '/api/public/emails-test': typeof ApiPublicEmailsTestRouteWithChildren
  '/cabinet/': typeof AuthenticatedCabinetIndexRoute
  '/api/public/emails-test/confirmer': typeof ApiPublicEmailsTestConfirmerRoute
  '/api/public/hooks/purge-donnees': typeof ApiPublicHooksPurgeDonneesRoute
  '/api/public/hooks/relance-pieces': typeof ApiPublicHooksRelancePiecesRoute
  '/api/public/hooks/relance-signatures': typeof ApiPublicHooksRelanceSignaturesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cgu': typeof CguRoute
  '/cgv': typeof CgvRoute
  '/commencer': typeof CommencerRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/rendez-vous': typeof RendezVousRoute
  '/simulateur': typeof SimulateurRoute
  '/tarifs': typeof TarifsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/creation': typeof AuthenticatedCreationRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/mon-compte': typeof AuthenticatedMonCompteRoute
  '/simulations': typeof AuthenticatedSimulationsRoute
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/verification-finale': typeof AuthenticatedVerificationFinaleRoute
  '/dev/apercu-statuts': typeof DevApercuStatutsRoute
  '/dev/associe-date': typeof DevAssocieDateRoute
  '/dev/conformite': typeof DevConformiteRoute
  '/dev/denomination': typeof DevDenominationRoute
  '/dev/wording-denomination': typeof DevWordingDenominationRoute
  '/signer/$jeton': typeof SignerJetonRoute
  '/cabinet/$id': typeof AuthenticatedCabinetIdRoute
  '/cabinet/conformite': typeof AuthenticatedCabinetConformiteRoute
  '/cabinet/contacts': typeof AuthenticatedCabinetContactsRoute
  '/cabinet/denominations': typeof AuthenticatedCabinetDenominationsRoute
  '/cabinet/donnees-test': typeof AuthenticatedCabinetDonneesTestRoute
  '/cabinet/emails-test': typeof AuthenticatedCabinetEmailsTestRoute
  '/cabinet/rappels': typeof AuthenticatedCabinetRappelsRoute
  '/api/public/emails-test': typeof ApiPublicEmailsTestRouteWithChildren
  '/cabinet': typeof AuthenticatedCabinetIndexRoute
  '/api/public/emails-test/confirmer': typeof ApiPublicEmailsTestConfirmerRoute
  '/api/public/hooks/purge-donnees': typeof ApiPublicHooksPurgeDonneesRoute
  '/api/public/hooks/relance-pieces': typeof ApiPublicHooksRelancePiecesRoute
  '/api/public/hooks/relance-signatures': typeof ApiPublicHooksRelanceSignaturesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cgu': typeof CguRoute
  '/cgv': typeof CgvRoute
  '/commencer': typeof CommencerRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/rendez-vous': typeof RendezVousRoute
  '/simulateur': typeof SimulateurRoute
  '/tarifs': typeof TarifsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/creation': typeof AuthenticatedCreationRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/mon-compte': typeof AuthenticatedMonCompteRoute
  '/_authenticated/simulations': typeof AuthenticatedSimulationsRoute
  '/_authenticated/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/_authenticated/verification-finale': typeof AuthenticatedVerificationFinaleRoute
  '/dev/apercu-statuts': typeof DevApercuStatutsRoute
  '/dev/associe-date': typeof DevAssocieDateRoute
  '/dev/conformite': typeof DevConformiteRoute
  '/dev/denomination': typeof DevDenominationRoute
  '/dev/wording-denomination': typeof DevWordingDenominationRoute
  '/signer/$jeton': typeof SignerJetonRoute
  '/_authenticated/cabinet/$id': typeof AuthenticatedCabinetIdRoute
  '/_authenticated/cabinet/conformite': typeof AuthenticatedCabinetConformiteRoute
  '/_authenticated/cabinet/contacts': typeof AuthenticatedCabinetContactsRoute
  '/_authenticated/cabinet/denominations': typeof AuthenticatedCabinetDenominationsRoute
  '/_authenticated/cabinet/donnees-test': typeof AuthenticatedCabinetDonneesTestRoute
  '/_authenticated/cabinet/emails-test': typeof AuthenticatedCabinetEmailsTestRoute
  '/_authenticated/cabinet/rappels': typeof AuthenticatedCabinetRappelsRoute
  '/api/public/emails-test': typeof ApiPublicEmailsTestRouteWithChildren
  '/_authenticated/cabinet/': typeof AuthenticatedCabinetIndexRoute
  '/api/public/emails-test/confirmer': typeof ApiPublicEmailsTestConfirmerRoute
  '/api/public/hooks/purge-donnees': typeof ApiPublicHooksPurgeDonneesRoute
  '/api/public/hooks/relance-pieces': typeof ApiPublicHooksRelancePiecesRoute
  '/api/public/hooks/relance-signatures': typeof ApiPublicHooksRelanceSignaturesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cgu'
    | '/cgv'
    | '/commencer'
    | '/confidentialite'
    | '/contact'
    | '/mentions-legales'
    | '/rendez-vous'
    | '/simulateur'
    | '/tarifs'
    | '/admin'
    | '/creation'
    | '/documents'
    | '/mon-compte'
    | '/simulations'
    | '/tableau-de-bord'
    | '/verification-finale'
    | '/dev/apercu-statuts'
    | '/dev/associe-date'
    | '/dev/conformite'
    | '/dev/denomination'
    | '/dev/wording-denomination'
    | '/signer/$jeton'
    | '/cabinet/$id'
    | '/cabinet/conformite'
    | '/cabinet/contacts'
    | '/cabinet/denominations'
    | '/cabinet/donnees-test'
    | '/cabinet/emails-test'
    | '/cabinet/rappels'
    | '/api/public/emails-test'
    | '/cabinet/'
    | '/api/public/emails-test/confirmer'
    | '/api/public/hooks/purge-donnees'
    | '/api/public/hooks/relance-pieces'
    | '/api/public/hooks/relance-signatures'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cgu'
    | '/cgv'
    | '/commencer'
    | '/confidentialite'
    | '/contact'
    | '/mentions-legales'
    | '/rendez-vous'
    | '/simulateur'
    | '/tarifs'
    | '/admin'
    | '/creation'
    | '/documents'
    | '/mon-compte'
    | '/simulations'
    | '/tableau-de-bord'
    | '/verification-finale'
    | '/dev/apercu-statuts'
    | '/dev/associe-date'
    | '/dev/conformite'
    | '/dev/denomination'
    | '/dev/wording-denomination'
    | '/signer/$jeton'
    | '/cabinet/$id'
    | '/cabinet/conformite'
    | '/cabinet/contacts'
    | '/cabinet/denominations'
    | '/cabinet/donnees-test'
    | '/cabinet/emails-test'
    | '/cabinet/rappels'
    | '/api/public/emails-test'
    | '/cabinet'
    | '/api/public/emails-test/confirmer'
    | '/api/public/hooks/purge-donnees'
    | '/api/public/hooks/relance-pieces'
    | '/api/public/hooks/relance-signatures'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cgu'
    | '/cgv'
    | '/commencer'
    | '/confidentialite'
    | '/contact'
    | '/mentions-legales'
    | '/rendez-vous'
    | '/simulateur'
    | '/tarifs'
    | '/_authenticated/admin'
    | '/_authenticated/creation'
    | '/_authenticated/documents'
    | '/_authenticated/mon-compte'
    | '/_authenticated/simulations'
    | '/_authenticated/tableau-de-bord'
    | '/_authenticated/verification-finale'
    | '/dev/apercu-statuts'
    | '/dev/associe-date'
    | '/dev/conformite'
    | '/dev/denomination'
    | '/dev/wording-denomination'
    | '/signer/$jeton'
    | '/_authenticated/cabinet/$id'
    | '/_authenticated/cabinet/conformite'
    | '/_authenticated/cabinet/contacts'
    | '/_authenticated/cabinet/denominations'
    | '/_authenticated/cabinet/donnees-test'
    | '/_authenticated/cabinet/emails-test'
    | '/_authenticated/cabinet/rappels'
    | '/api/public/emails-test'
    | '/_authenticated/cabinet/'
    | '/api/public/emails-test/confirmer'
    | '/api/public/hooks/purge-donnees'
    | '/api/public/hooks/relance-pieces'
    | '/api/public/hooks/relance-signatures'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CguRoute: typeof CguRoute
  CgvRoute: typeof CgvRoute
  CommencerRoute: typeof CommencerRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  RendezVousRoute: typeof RendezVousRoute
  SimulateurRoute: typeof SimulateurRoute
  TarifsRoute: typeof TarifsRoute
  DevApercuStatutsRoute: typeof DevApercuStatutsRoute
  DevAssocieDateRoute: typeof DevAssocieDateRoute
  DevConformiteRoute: typeof DevConformiteRoute
  DevDenominationRoute: typeof DevDenominationRoute
  DevWordingDenominationRoute: typeof DevWordingDenominationRoute
  SignerJetonRoute: typeof SignerJetonRoute
  ApiPublicEmailsTestRoute: typeof ApiPublicEmailsTestRouteWithChildren
  ApiPublicHooksPurgeDonneesRoute: typeof ApiPublicHooksPurgeDonneesRoute
  ApiPublicHooksRelancePiecesRoute: typeof ApiPublicHooksRelancePiecesRoute
  ApiPublicHooksRelanceSignaturesRoute: typeof ApiPublicHooksRelanceSignaturesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commencer': {
      id: '/commencer'
      path: '/commencer'
      fullPath: '/commencer'
      preLoaderRoute: typeof CommencerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rendez-vous': {
      id: '/rendez-vous'
      path: '/rendez-vous'
      fullPath: '/rendez-vous'
      preLoaderRoute: typeof RendezVousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulateur': {
      id: '/simulateur'
      path: '/simulateur'
      fullPath: '/simulateur'
      preLoaderRoute: typeof SimulateurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/creation': {
      id: '/_authenticated/creation'
      path: '/creation'
      fullPath: '/creation'
      preLoaderRoute: typeof AuthenticatedCreationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon-compte': {
      id: '/_authenticated/mon-compte'
      path: '/mon-compte'
      fullPath: '/mon-compte'
      preLoaderRoute: typeof AuthenticatedMonCompteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/simulations': {
      id: '/_authenticated/simulations'
      path: '/simulations'
      fullPath: '/simulations'
      preLoaderRoute: typeof AuthenticatedSimulationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tableau-de-bord': {
      id: '/_authenticated/tableau-de-bord'
      path: '/tableau-de-bord'
      fullPath: '/tableau-de-bord'
      preLoaderRoute: typeof AuthenticatedTableauDeBordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/verification-finale': {
      id: '/_authenticated/verification-finale'
      path: '/verification-finale'
      fullPath: '/verification-finale'
      preLoaderRoute: typeof AuthenticatedVerificationFinaleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/dev/apercu-statuts': {
      id: '/dev/apercu-statuts'
      path: '/dev/apercu-statuts'
      fullPath: '/dev/apercu-statuts'
      preLoaderRoute: typeof DevApercuStatutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/associe-date': {
      id: '/dev/associe-date'
      path: '/dev/associe-date'
      fullPath: '/dev/associe-date'
      preLoaderRoute: typeof DevAssocieDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/conformite': {
      id: '/dev/conformite'
      path: '/dev/conformite'
      fullPath: '/dev/conformite'
      preLoaderRoute: typeof DevConformiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/denomination': {
      id: '/dev/denomination'
      path: '/dev/denomination'
      fullPath: '/dev/denomination'
      preLoaderRoute: typeof DevDenominationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/wording-denomination': {
      id: '/dev/wording-denomination'
      path: '/dev/wording-denomination'
      fullPath: '/dev/wording-denomination'
      preLoaderRoute: typeof DevWordingDenominationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signer/$jeton': {
      id: '/signer/$jeton'
      path: '/signer/$jeton'
      fullPath: '/signer/$jeton'
      preLoaderRoute: typeof SignerJetonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cabinet/': {
      id: '/_authenticated/cabinet/'
      path: '/cabinet'
      fullPath: '/cabinet/'
      preLoaderRoute: typeof AuthenticatedCabinetIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cabinet/$id': {
      id: '/_authenticated/cabinet/$id'
      path: '/cabinet/$id'
      fullPath: '/cabinet/$id'
      preLoaderRoute: typeof AuthenticatedCabinetIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cabinet/conformite': {
      id: '/_authenticated/cabinet/conformite'
      path: '/cabinet/conformite'
      fullPath: '/cabinet/conformite'
      preLoaderRoute: typeof AuthenticatedCabinetConformiteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cabinet/contacts': {
      id: '/_authenticated/cabinet/contacts'
      path: '/cabinet/contacts'
      fullPath: '/cabinet/contacts'
      preLoaderRoute: typeof AuthenticatedCabinetContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cabinet/denominations': {
      id: '/_authenticated/cabinet/denominations'
      path: '/cabinet/denominations'
      fullPath: '/cabinet/denominations'
      preLoaderRoute: typeof AuthenticatedCabinetDenominationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cabinet/donnees-test': {
      id: '/_authenticated/cabinet/donnees-test'
      path: '/cabinet/donnees-test'
      fullPath: '/cabinet/donnees-test'
      preLoaderRoute: typeof AuthenticatedCabinetDonneesTestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cabinet/emails-test': {
      id: '/_authenticated/cabinet/emails-test'
      path: '/cabinet/emails-test'
      fullPath: '/cabinet/emails-test'
      preLoaderRoute: typeof AuthenticatedCabinetEmailsTestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cabinet/rappels': {
      id: '/_authenticated/cabinet/rappels'
      path: '/cabinet/rappels'
      fullPath: '/cabinet/rappels'
      preLoaderRoute: typeof AuthenticatedCabinetRappelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/emails-test': {
      id: '/api/public/emails-test'
      path: '/api/public/emails-test'
      fullPath: '/api/public/emails-test'
      preLoaderRoute: typeof ApiPublicEmailsTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/emails-test/confirmer': {
      id: '/api/public/emails-test/confirmer'
      path: '/confirmer'
      fullPath: '/api/public/emails-test/confirmer'
      preLoaderRoute: typeof ApiPublicEmailsTestConfirmerRouteImport
      parentRoute: typeof ApiPublicEmailsTestRoute
    }
    '/api/public/hooks/purge-donnees': {
      id: '/api/public/hooks/purge-donnees'
      path: '/api/public/hooks/purge-donnees'
      fullPath: '/api/public/hooks/purge-donnees'
      preLoaderRoute: typeof ApiPublicHooksPurgeDonneesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/relance-pieces': {
      id: '/api/public/hooks/relance-pieces'
      path: '/api/public/hooks/relance-pieces'
      fullPath: '/api/public/hooks/relance-pieces'
      preLoaderRoute: typeof ApiPublicHooksRelancePiecesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/relance-signatures': {
      id: '/api/public/hooks/relance-signatures'
      path: '/api/public/hooks/relance-signatures'
      fullPath: '/api/public/hooks/relance-signatures'
      preLoaderRoute: typeof ApiPublicHooksRelanceSignaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCreationRoute: typeof AuthenticatedCreationRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedMonCompteRoute: typeof AuthenticatedMonCompteRoute
  AuthenticatedSimulationsRoute: typeof AuthenticatedSimulationsRoute
  AuthenticatedTableauDeBordRoute: typeof AuthenticatedTableauDeBordRoute
  AuthenticatedVerificationFinaleRoute: typeof AuthenticatedVerificationFinaleRoute
  AuthenticatedCabinetIdRoute: typeof AuthenticatedCabinetIdRoute
  AuthenticatedCabinetConformiteRoute: typeof AuthenticatedCabinetConformiteRoute
  AuthenticatedCabinetContactsRoute: typeof AuthenticatedCabinetContactsRoute
  AuthenticatedCabinetDenominationsRoute: typeof AuthenticatedCabinetDenominationsRoute
  AuthenticatedCabinetDonneesTestRoute: typeof AuthenticatedCabinetDonneesTestRoute
  AuthenticatedCabinetEmailsTestRoute: typeof AuthenticatedCabinetEmailsTestRoute
  AuthenticatedCabinetRappelsRoute: typeof AuthenticatedCabinetRappelsRoute
  AuthenticatedCabinetIndexRoute: typeof AuthenticatedCabinetIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCreationRoute: AuthenticatedCreationRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedMonCompteRoute: AuthenticatedMonCompteRoute,
  AuthenticatedSimulationsRoute: AuthenticatedSimulationsRoute,
  AuthenticatedTableauDeBordRoute: AuthenticatedTableauDeBordRoute,
  AuthenticatedVerificationFinaleRoute: AuthenticatedVerificationFinaleRoute,
  AuthenticatedCabinetIdRoute: AuthenticatedCabinetIdRoute,
  AuthenticatedCabinetConformiteRoute: AuthenticatedCabinetConformiteRoute,
  AuthenticatedCabinetContactsRoute: AuthenticatedCabinetContactsRoute,
  AuthenticatedCabinetDenominationsRoute:
    AuthenticatedCabinetDenominationsRoute,
  AuthenticatedCabinetDonneesTestRoute: AuthenticatedCabinetDonneesTestRoute,
  AuthenticatedCabinetEmailsTestRoute: AuthenticatedCabinetEmailsTestRoute,
  AuthenticatedCabinetRappelsRoute: AuthenticatedCabinetRappelsRoute,
  AuthenticatedCabinetIndexRoute: AuthenticatedCabinetIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicEmailsTestRouteChildren {
  ApiPublicEmailsTestConfirmerRoute: typeof ApiPublicEmailsTestConfirmerRoute
}

const ApiPublicEmailsTestRouteChildren: ApiPublicEmailsTestRouteChildren = {
  ApiPublicEmailsTestConfirmerRoute: ApiPublicEmailsTestConfirmerRoute,
}

const ApiPublicEmailsTestRouteWithChildren =
  ApiPublicEmailsTestRoute._addFileChildren(ApiPublicEmailsTestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CguRoute: CguRoute,
  CgvRoute: CgvRoute,
  CommencerRoute: CommencerRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  RendezVousRoute: RendezVousRoute,
  SimulateurRoute: SimulateurRoute,
  TarifsRoute: TarifsRoute,
  DevApercuStatutsRoute: DevApercuStatutsRoute,
  DevAssocieDateRoute: DevAssocieDateRoute,
  DevConformiteRoute: DevConformiteRoute,
  DevDenominationRoute: DevDenominationRoute,
  DevWordingDenominationRoute: DevWordingDenominationRoute,
  SignerJetonRoute: SignerJetonRoute,
  ApiPublicEmailsTestRoute: ApiPublicEmailsTestRouteWithChildren,
  ApiPublicHooksPurgeDonneesRoute: ApiPublicHooksPurgeDonneesRoute,
  ApiPublicHooksRelancePiecesRoute: ApiPublicHooksRelancePiecesRoute,
  ApiPublicHooksRelanceSignaturesRoute: ApiPublicHooksRelanceSignaturesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
